-- Users Table
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  client text,
  created_at timestamptz default now()
);

-- Tags Table
create table if not exists tags (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null
);

-- Accounts Table
create table if not exists accounts (
  id bigint generated by default as identity primary key,
  issuer text not null,
  account text not null,
  secret text not null,
  created_at timestamptz default now()
);

-- Account_Tags Join Table
create table if not exists account_tags (
  account_id bigint references accounts(id) on delete cascade,
  tag_id bigint references tags(id) on delete cascade,
  primary key (account_id, tag_id)
);

-- RLS Policies (Optional but recommended for Supabase)
alter table users enable row level security;
alter table tags enable row level security;
alter table accounts enable row level security;
alter table account_tags enable row level security;

-- For simple backend usage (service role), we can allow all,
-- but strictly speaking for a secure app you'd want proper policies.
-- For now, to match SQLite behavior (no auth checks at DB level), we permit all for authenticated/anon if needed,
-- OR we rely on the fact that our Next.js backend uses the SERVICE_ROLE_KEY or strictly controls access.
-- However, standard Supabase client usually uses the public ANON key.
-- If we use the SERVICE_ROLE key in the backend, RLS is bypassed.
-- If we use ANON key, we need policies.
-- Let's assume we want to be safe and add basic policies allowing access.

create policy "Allow full access to service role" on users for all using (true) with check (true);
create policy "Allow full access to service role" on tags for all using (true) with check (true);
create policy "Allow full access to service role" on accounts for all using (true) with check (true);
create policy "Allow full access to service role" on account_tags for all using (true) with check (true);

-- Insert default admin if not exists
insert into users (name, email, client)
values ('admin', 'admin@example.com', 'default')
on conflict do nothing;
